var GAME_FPS = 60;

var CHARACTER_SPRITE_COLS = 4;
var CHARACTER_SPRITE_ROWS = 1;
var CHARACTER_FRAMES_BY_SPRITE = 4;

var CHARACTER_WIDTH = 32;
var CHARACTER_HEIGHT = 32;

var CHAR_INIT_POSX = 0.1*1920;
var CHAR_INIT_POSY = 0.9*1080;
