var MAP_TILE_WIDTH = 32;
var MAP_TILE_HEIGHT = 16;

var BACKGROUND_TEXTURE_WIDTH = 128;
var BACKGROUND_TEXTURE_HEIGHT = 64;

var BACKGROUND_CHARACTER_WIDTH = 128;
var BACKGROUND_CHARACTER_HEIGHT = 256;