var MAP_TILE_WIDTH = 32;
var MAP_TILE_HEIGHT = 16;

var BACKGROUND_TILE_WIDTH = 80;
var BACKGROUND_TILE_HEIGHT = 36;
var BACKGROUND_TEXTURE_WIDTH = 128;
var BACKGROUND_TEXTURE_HEIGHT = 64;
var BACKGROUND_X_OFFSET = 12;
var BACKGROUND_Y_OFFSET = 4;
